services:
  fitracker-db:
    container_name: fitracker-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  fitracker-api:
    container_name: fitracker-api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run start:debug # override npm run start:dev in Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: fitracker-db
    ports:
      - '3000:3000'
      - '9229:9229' # debug port
    depends_on:
      - fitracker-db
    # Mount host directory to docker container (for hot reloading)
    volumes:
      - .:/usr/src/app:delegated
      - /usr/src/app/node_modules # excludes node_modules

  test-db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - '5433:5432'

  # used when running npm run seed (for seeding the database)
  seed:
    image: postgres:15
    depends_on:
      - fitracker-db
    environment:
      PGHOST: fitracker-db
      PGUSER: ${POSTGRES_USER}
      PGDATABASE: ${POSTGRES_DATABASE}
      PGPASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./scripts/run-seeds.sh:/scripts/run-seeds.sh
      - ./database/seeds:/database/seeds
    entrypoint: ['sh', '/scripts/run-seeds.sh']

volumes:
  pgdata:
