version: '3.9'

services:
  fitracker-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  # testdb:
  #   container_name: test-db
  #   image: postgres:15
  #   restart: always
  #   environment:
  #     POSTGRES_USER: testuser
  #     POSTGRES_PASSWORD: testpassword
  #     POSTGRES_DB: testdb
  #   ports:@#@
  #     - '5433:5432'

  fitracker-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:debug
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: db
    ports:
      - '3000:3000'
      - '9229:9229' # debug port
    depends_on:
      - fitracker-db
    # Mount host directory to docker container (for hot reloading)
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  seed:
    image: postgres:15
    depends_on:
      - fitracker-db
    environment:
      PGHOST: fitracker-db
      PGUSER: ${POSTGRES_USER}
      PGDATABASE: ${POSTGRES_DATABASE}
      PGPASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./database/seeds:/database/seeds
      - ./scripts/run-seeds.sh:/scripts/run-seeds.sh
    entrypoint: ['sh', '/scripts/run-seeds.sh']

volumes:
  pgdata:
