name: Production Database Migration

on:
  pull_request:
    branches:
      - main

jobs:
  prod-db-migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push migration image to Docker Hub
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t calebjanhunen/db-migrate:latest \
            --push ./database

      - name: Pull migration image
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.RPI_IP }}
          username: ${{ secrets.RPI_USER }}
          key: ${{ secrets.RPI_SSH_KEY }}
          port: ${{ secrets.RPI_SSH_PORT }}
          script: |
            echo "Logging into Docker..."
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            echo "Pulling the new image..."
            docker pull calebjanhunen/db-migrate:latest

      - name: Run migrations
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.RPI_IP }}
          username: ${{ secrets.RPI_USER }}
          key: ${{ secrets.RPI_SSH_KEY }}
          port: ${{ secrets.RPI_SSH_PORT }}
          script: |
            echo "Running migrations"
            docker run --rm \
               -e POSTGRES_HOST=$POSTGRES_HOST \
               -e POSTGRES_PORT=$POSTGRES_PORT \
               -e POSTGRES_USER=$POSTGRES_USER \
               -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
               -e POSTGRES_DATABAS=$POSTGRES_DATABASE \
               calebjanhunen/db-migrate:latest
